server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gx_springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  #实体类所在包名
  type-aliases-package: com.example.entity
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mybatis/**/*Mapper.xml

  #通用mapper配置
  mapper:
    #公用接口类路径  通用mapper不能和普通的放在一个包下
    mappers: com.example.baseMapper.BaseMapper
    identity: MYSQL

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#mybatis分页插件配置
pagehelper:
  helper-dialect: mysql  #数据库
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

